package com.example.citygisproject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MessageDesign extends VerticalLayout {
	protected Label message_header;
	protected Label message_content;
	protected Button message_btn1;
	protected Button message_btn2;
	protected Button message_btn3;
	protected Button message_btn4;

	public MessageDesign() {
		Design.read(this);
	}
}
